CREATE TABLE IF NOT EXISTS USERS(
ID INT, USER_LOGIN VARCHAR(30), USER_PASS VARCHAR(30), AGE INT);
INSERT INTO USERS VALUES(1, 'a','a', 15);
INSERT INTO USERS VALUES(2, 'b','b', 21);
INSERT INTO USERS VALUES(3, 'c','c', 30);